Implementing missing OrderedSet methods
Has been receiving:

error: Cannot instantiate abstract class 'OrderedSet' with abstract attributes '__contains__', '__iter__' and '__len__'